---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: xrspace-studio-drone
roleRef:
  kind: Role
  name: xrspace-studio-drone-helm
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    namespace: default
    name: xrspace-studio-drone
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: xrspace-studio-drone-helm
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - secrets
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete  
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete  
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete  
- apiGroups:
  - traefik.containo.us
  resources:
  - ingressroutes
  - ingressroutetcps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch